version: '3.8'

services:
  # Sua API Rust
  app:
    build: .
    container_name: rust-api-lab
    ports:
      - "3000:3000"
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    depends_on:
      - localstack

  # O Simulador da AWS
  localstack:
    image: localstack/localstack:3.0
    container_name: localstack_main
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DNS_ADDRESS=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
