apiVersion: v1
kind: Secret
metadata:
  name: rust-api-secrets
type: Opaque
stringData:
  AWS_ENDPOINT_URL: "http://localstack:4566"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  AWS_REGION: "us-east-1"
  BUCKET_NAME: "rust-cloud-lab-logs"
