name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:3.0
        ports:
          - 4566:4566
        env:
          DNS_ADDRESS: "0"
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Rust Install
        uses: dtolnay/rust-toolchain@stable
      - name: Dependency Cache
        uses: Swatinem/rust-cache@v2
      - name: Run Tests
        run: cargo test
        env:
          AWS_ENDPOINT_URL: http://localhost:4566
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_REGION: us-east-1
          BUCKET_NAME: rust-cloud-lab-test
          QUEUE_NAME: rust-cloud-lab-queue-test
